baseURL = 'https://quiet-cactus-457f5b.netlify.app/'
languageCode = 'en-us'
title = 'Dansk Bjergklub Arkiv'
theme = "etch"

[menu]
  [[menu.main]]
    identifier = "search"
    name = "search"
    title = "search"
    url = "/search/"
    weight = 20
