[build]
  command = "hugo && npx -y pagefind --source public"
  publish = "public"

[build.environment]
  HUGO_VERSION = "v0.105.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
